### ISSUE TITLE
クラス使う考えはすごい！

### ISSUE THREAD

**Issue by C0B21061** [C0B21133/ProjExD#7]
https://github.com/C0B21133/ProjExD/blob/23ce0153c9a47078d42c9593c32b23eaef0f1401/ex02/calc.py#L4
クラスを使う考えは思い浮かばなかったです。きれいにまとめられていて見やすいです。

**Comment by C0B21133** [comment]
クラスを使って綺麗にまとめられたので良かったです。
ありがとうございます
